parameters:
        
           
           files_ids: /media/DATA2/ersan/deneme/human_pubmed_ids/
           files_abstracts: /media/DATA2/ersan/deneme/human_pubmed_abstracts/
           error_file: /media/DATA2/ersan/deneme/pubmed_yeni_abstractlar/error_abstract.txt
