parameters:
        removing_parentheses:
           files_par: /media/DATA/amine/deneme/son/  
           old_file_par: /media/DATA/amine/deneme/son/
           new_file_par: /media/DATA/amine/deneme/uniprot_par/ 

        removing_dots:
           files_dot: /media/DATA/amine/deneme/uniprot_par/  
           old_file_dot: /media/DATA/amine/deneme/uniprot_par/
           new_file_dot: /media/DATA/amine/deneme/uniprot_dot/

        removing_spaces:
           files_space: /media/DATA/amine/deneme/uniprot_dot/  
           old_file_space: /media/DATA/amine/deneme/uniprot_dot/
           new_file_space: /media/DATA/amine/deneme/uniprot_space/  
             
