parameters: 
        uniprot_dir: /media/DATA2/ersan/uniprot_sprot.xml.gz                       
        new_file_dir: /media/DATA2/ersan/deneme/son/ 
        error_file_dir: /media/DATA2/ersan/deneme/error_file  