parameters:
        removing_parentheses:
           files_par: /media/DATA2/ersan/deneme/son/  
           old_file_par: /media/DATA2/ersan/deneme/son/
           new_file_par: /media/DATA2/ersan/deneme/uniprot_par/

        removing_dots:
           files_dot: /media/DATA2/ersan/deneme/uniprot_par/  
           old_file_dot: /media/DATA2/ersan/deneme/uniprot_par/
           new_file_dot: /media/DATA2/ersan/deneme/uniprot_dot/

        removing_spaces:
           files_space: /media/DATA2/ersan/deneme/uniprot_dot/  
           old_file_space: /media/DATA2/ersan/deneme/uniprot_dot/
           new_file_space: "/media/DATA2/ersan/deneme/uniprot_space/"  
             
